insert into category (categoryId, categoryname) values (1, 'Structural & Misc Steel Erection');
insert into category (categoryId, categoryname) values (2, 'Retaining Wall and Brick Pavers');
insert into category (categoryId, categoryname) values (3, 'Doors, Frames & Hardware');
insert into category (categoryId, categoryname) values (4, 'Painting & Vinyl Wall Covering');
insert into category (categoryId, categoryname) values (5, 'Drywall & Acoustical (FED)');
insert into category (categoryId, categoryname) values (6, 'Hard Tile & Stone');
insert into category (categoryId, categoryname) values (7, 'Drilled Shafts');
insert into category (categoryId, categoryname) values (8, 'Structural & Misc Steel Erection');
insert into category (categoryId, categoryname) values (9, 'Roofing (Metal)');
insert into category (categoryId, categoryname) values (10, 'Masonry');
insert into category (categoryId, categoryname) values (11, 'Electrical');
insert into category (categoryId, categoryname) values (12, 'Masonry');
insert into category (categoryId, categoryname) values (13, 'Granite Surfaces');
insert into category (categoryId, categoryname) values (14, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (categoryId, categoryname) values (15, 'Granite Surfaces');
insert into category (categoryId, categoryname) values (16, 'Fire Protection');
insert into category (categoryId, categoryname) values (17, 'Rebar & Wire Mesh Install');
insert into category (categoryId, categoryname) values (18, 'Soft Flooring and Base');
insert into category (categoryId, categoryname) values (19, 'Masonry & Precast');
insert into category (categoryId, categoryname) values (20, 'Overhead Doors');
insert into category (categoryId, categoryname) values (21, 'HVAC');
insert into category (categoryId, categoryname) values (22, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (categoryId, categoryname) values (23, 'Casework');
insert into category (categoryId, categoryname) values (24, 'Roofing (Metal)');
insert into category (categoryId, categoryname) values (25, 'Framing (Wood)');
insert into category (categoryId, categoryname) values (26, 'Doors, Frames & Hardware');
insert into category (categoryId, categoryname) values (27, 'Landscaping & Irrigation');
insert into category (categoryId, categoryname) values (28, 'Rebar & Wire Mesh Install');
insert into category (categoryId, categoryname) values (29, 'Overhead Doors');
insert into category (categoryId, categoryname) values (30, 'Site Furnishings');
insert into category (categoryId, categoryname) values (31, 'Landscaping & Irrigation');
insert into category (categoryId, categoryname) values (32, 'Overhead Doors');
insert into category (categoryId, categoryname) values (33, 'Wall Protection');
insert into category (categoryId, categoryname) values (34, 'Casework');
insert into category (categoryId, categoryname) values (35, 'Structural & Misc Steel Erection');
insert into category (categoryId, categoryname) values (36, 'Electrical');
insert into category (categoryId, categoryname) values (37, 'Glass & Glazing');
insert into category (categoryId, categoryname) values (38, 'Roofing (Asphalt)');
insert into category (categoryId, categoryname) values (39, 'Drilled Shafts');
insert into category (categoryId, categoryname) values (40, 'Site Furnishings');
insert into category (categoryId, categoryname) values (41, 'Prefabricated Aluminum Metal Canopies');
insert into category (categoryId, categoryname) values (42, 'Drywall & Acoustical (MOB)');
insert into category (categoryId, categoryname) values (43, 'Electrical');
insert into category (categoryId, categoryname) values (44, 'Electrical and Fire Alarm');
insert into category (categoryId, categoryname) values (45, 'Sitework & Site Utilities');
insert into category (categoryId, categoryname) values (46, 'Masonry');
insert into category (categoryId, categoryname) values (47, 'HVAC');
insert into category (categoryId, categoryname) values (48, 'Retaining Wall and Brick Pavers');
insert into category (categoryId, categoryname) values (49, 'Exterior Signage');
insert into category (categoryId, categoryname) values (50, 'Fire Sprinkler System');
insert into category (categoryId, categoryname) values (51, 'Fire Sprinkler System');
insert into category (categoryId, categoryname) values (52, 'HVAC');
insert into category (categoryId, categoryname) values (53, 'Glass & Glazing');
insert into category (categoryId, categoryname) values (54, 'Sitework & Site Utilities');
insert into category (categoryId, categoryname) values (55, 'Framing (Wood)');
insert into category (categoryId, categoryname) values (56, 'Sitework & Site Utilities');
insert into category (categoryId, categoryname) values (57, 'Casework');
insert into category (categoryId, categoryname) values (58, 'Drywall & Acoustical (MOB)');
insert into category (categoryId, categoryname) values (59, 'Roofing (Metal)');
insert into category (categoryId, categoryname) values (60, 'Asphalt Paving');
insert into category (categoryId, categoryname) values (61, 'Prefabricated Aluminum Metal Canopies');
insert into category (categoryId, categoryname) values (62, 'Granite Surfaces');
insert into category (categoryId, categoryname) values (63, 'HVAC');
insert into category (categoryId, categoryname) values (64, 'Waterproofing & Caulking');
insert into category (categoryId, categoryname) values (65, 'Plumbing & Medical Gas');
insert into category (categoryId, categoryname) values (66, 'Overhead Doors');
insert into category (categoryId, categoryname) values (67, 'Waterproofing & Caulking');
insert into category (categoryId, categoryname) values (68, 'Site Furnishings');
insert into category (categoryId, categoryname) values (69, 'Granite Surfaces');
insert into category (categoryId, categoryname) values (70, 'Waterproofing & Caulking');
insert into category (categoryId, categoryname) values (71, 'Termite Control');
insert into category (categoryId, categoryname) values (72, 'HVAC');
insert into category (categoryId, categoryname) values (73, 'Roofing (Metal)');
insert into category (categoryId, categoryname) values (74, 'Structural and Misc Steel (Fabrication)');
insert into category (categoryId, categoryname) values (75, 'Hard Tile & Stone');
insert into category (categoryId, categoryname) values (76, 'Site Furnishings');
insert into category (categoryId, categoryname) values (77, 'Overhead Doors');
insert into category (categoryId, categoryname) values (78, 'Termite Control');
insert into category (categoryId, categoryname) values (79, 'Elevator');
insert into category (categoryId, categoryname) values (80, 'Waterproofing & Caulking');
insert into category (categoryId, categoryname) values (81, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (categoryId, categoryname) values (82, 'Prefabricated Aluminum Metal Canopies');
insert into category (categoryId, categoryname) values (83, 'Granite Surfaces');
insert into category (categoryId, categoryname) values (84, 'Granite Surfaces');
insert into category (categoryId, categoryname) values (85, 'Drilled Shafts');
insert into category (categoryId, categoryname) values (86, 'Framing (Steel)');
insert into category (categoryId, categoryname) values (87, 'Rebar & Wire Mesh Install');
insert into category (categoryId, categoryname) values (88, 'Elevator');
insert into category (categoryId, categoryname) values (89, 'Glass & Glazing');
insert into category (categoryId, categoryname) values (90, 'Fire Sprinkler System');
insert into category (categoryId, categoryname) values (91, 'Retaining Wall and Brick Pavers');
insert into category (categoryId, categoryname) values (92, 'Drywall & Acoustical (MOB)');
insert into category (categoryId, categoryname) values (93, 'Glass & Glazing');
insert into category (categoryId, categoryname) values (94, 'Framing (Wood)');
insert into category (categoryId, categoryname) values (95, 'Drywall & Acoustical (MOB)');
insert into category (categoryId, categoryname) values (96, 'Fire Protection');
insert into category (categoryId, categoryname) values (97, 'Electrical and Fire Alarm');
insert into category (categoryId, categoryname) values (98, 'Drilled Shafts');
insert into category (categoryId, categoryname) values (99, 'Prefabricated Aluminum Metal Canopies');
insert into category (categoryId, categoryname) values (100, 'Asphalt Paving');
insert into category (categoryId, categoryname) values (101, 'Marlite Panels (FED)');
insert into category (categoryId, categoryname) values (102, 'Casework');
insert into category (categoryId, categoryname) values (103, 'Structural and Misc Steel (Fabrication)');
insert into category (categoryId, categoryname) values (104, 'Sitework & Site Utilities');
insert into category (categoryId, categoryname) values (105, 'Drywall & Acoustical (FED)');
insert into category (categoryId, categoryname) values (106, 'Plumbing & Medical Gas');
insert into category (categoryId, categoryname) values (107, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (categoryId, categoryname) values (108, 'Masonry');
insert into category (categoryId, categoryname) values (109, 'RF Shielding');
insert into category (categoryId, categoryname) values (110, 'Retaining Wall and Brick Pavers');
insert into category (categoryId, categoryname) values (111, 'Termite Control');
insert into category (categoryId, categoryname) values (112, 'Rebar & Wire Mesh Install');
insert into category (categoryId, categoryname) values (113, 'Exterior Signage');
insert into category (categoryId, categoryname) values (114, 'Landscaping & Irrigation');
insert into category (categoryId, categoryname) values (115, 'Masonry');
insert into category (categoryId, categoryname) values (116, 'Drywall & Acoustical (MOB)');
insert into category (categoryId, categoryname) values (117, 'Framing (Steel)');
insert into category (categoryId, categoryname) values (118, 'Masonry & Precast');
insert into category (categoryId, categoryname) values (119, 'Overhead Doors');
insert into category (categoryId, categoryname) values (120, 'Site Furnishings');
insert into category (categoryId, categoryname) values (121, 'Waterproofing & Caulking');
insert into category (categoryId, categoryname) values (122, 'Termite Control');
insert into category (categoryId, categoryname) values (123, 'Wall Protection');
insert into category (categoryId, categoryname) values (124, 'Plumbing & Medical Gas');
insert into category (categoryId, categoryname) values (125, 'Structural and Misc Steel (Fabrication)');
insert into category (categoryId, categoryname) values (126, 'Framing (Steel)');
insert into category (categoryId, categoryname) values (127, 'Doors, Frames & Hardware');
insert into category (categoryId, categoryname) values (128, 'Framing (Wood)');
insert into category (categoryId, categoryname) values (129, 'Structural and Misc Steel (Fabrication)');
insert into category (categoryId, categoryname) values (130, 'Retaining Wall and Brick Pavers');
insert into category (categoryId, categoryname) values (131, 'Masonry & Precast');
insert into category (categoryId, categoryname) values (132, 'Overhead Doors');
insert into category (categoryId, categoryname) values (133, 'Prefabricated Aluminum Metal Canopies');
insert into category (categoryId, categoryname) values (134, 'Ornamental Railings');
insert into category (categoryId, categoryname) values (135, 'Site Furnishings');
insert into category (categoryId, categoryname) values (136, 'Overhead Doors');
insert into category (categoryId, categoryname) values (137, 'Ornamental Railings');
insert into category (categoryId, categoryname) values (138, 'Curb & Gutter');
insert into category (categoryId, categoryname) values (139, 'Waterproofing & Caulking');
insert into category (categoryId, categoryname) values (140, 'Plumbing & Medical Gas');
insert into category (categoryId, categoryname) values (141, 'Structural and Misc Steel (Fabrication)');
insert into category (categoryId, categoryname) values (142, 'Hard Tile & Stone');
insert into category (categoryId, categoryname) values (143, 'Doors, Frames & Hardware');
insert into category (categoryId, categoryname) values (144, 'Asphalt Paving');
insert into category (categoryId, categoryname) values (145, 'Landscaping & Irrigation');
insert into category (categoryId, categoryname) values (146, 'Masonry & Precast');
insert into category (categoryId, categoryname) values (147, 'Masonry & Precast');
insert into category (categoryId, categoryname) values (148, 'Sitework & Site Utilities');
insert into category (categoryId, categoryname) values (149, 'Overhead Doors');
insert into category (categoryId, categoryname) values (150, 'Construction Clean and Final Clean');
insert into category (categoryId, categoryname) values (151, 'Overhead Doors');
insert into category (categoryId, categoryname) values (152, 'Ornamental Railings');
insert into category (categoryId, categoryname) values (153, 'Glass & Glazing');
insert into category (categoryId, categoryname) values (154, 'Ornamental Railings');
insert into category (categoryId, categoryname) values (155, 'Masonry & Precast');
insert into category (categoryId, categoryname) values (156, 'Elevator');
insert into category (categoryId, categoryname) values (157, 'Granite Surfaces');
insert into category (categoryId, categoryname) values (158, 'Structural & Misc Steel Erection');
insert into category (categoryId, categoryname) values (159, 'Waterproofing & Caulking');
insert into category (categoryId, categoryname) values (160, 'Exterior Signage');
insert into category (categoryId, categoryname) values (161, 'Drywall & Acoustical (MOB)');
insert into category (categoryId, categoryname) values (162, 'Asphalt Paving');
insert into category (categoryId, categoryname) values (163, 'Retaining Wall and Brick Pavers');
insert into category (categoryId, categoryname) values (164, 'Roofing (Asphalt)');
insert into category (categoryId, categoryname) values (165, 'HVAC');
insert into category (categoryId, categoryname) values (166, 'Construction Clean and Final Clean');
insert into category (categoryId, categoryname) values (167, 'Granite Surfaces');
insert into category (categoryId, categoryname) values (168, 'Casework');
insert into category (categoryId, categoryname) values (169, 'Drywall & Acoustical (FED)');
insert into category (categoryId, categoryname) values (170, 'Prefabricated Aluminum Metal Canopies');
insert into category (categoryId, categoryname) values (171, 'Termite Control');
insert into category (categoryId, categoryname) values (172, 'HVAC');
insert into category (categoryId, categoryname) values (173, 'RF Shielding');
insert into category (categoryId, categoryname) values (174, 'Soft Flooring and Base');
insert into category (categoryId, categoryname) values (175, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (categoryId, categoryname) values (176, 'Masonry & Precast');
insert into category (categoryId, categoryname) values (177, 'Masonry');
insert into category (categoryId, categoryname) values (178, 'Granite Surfaces');
insert into category (categoryId, categoryname) values (179, 'Structural and Misc Steel (Fabrication)');
insert into category (categoryId, categoryname) values (180, 'Framing (Wood)');
insert into category (categoryId, categoryname) values (181, 'Soft Flooring and Base');
insert into category (categoryId, categoryname) values (182, 'Sitework & Site Utilities');
insert into category (categoryId, categoryname) values (183, 'Drywall & Acoustical (MOB)');
insert into category (categoryId, categoryname) values (184, 'Masonry');
insert into category (categoryId, categoryname) values (185, 'Epoxy Flooring');
insert into category (categoryId, categoryname) values (186, 'Roofing (Metal)');
insert into category (categoryId, categoryname) values (187, 'Exterior Signage');
insert into category (categoryId, categoryname) values (188, 'Drilled Shafts');
insert into category (categoryId, categoryname) values (189, 'Asphalt Paving');
insert into category (categoryId, categoryname) values (190, 'Termite Control');
insert into category (categoryId, categoryname) values (191, 'Drilled Shafts');
insert into category (categoryId, categoryname) values (192, 'Painting & Vinyl Wall Covering');
insert into category (categoryId, categoryname) values (193, 'Sitework & Site Utilities');
insert into category (categoryId, categoryname) values (194, 'Overhead Doors');
insert into category (categoryId, categoryname) values (195, 'Fire Protection');
insert into category (categoryId, categoryname) values (196, 'Fire Sprinkler System');
insert into category (categoryId, categoryname) values (197, 'Construction Clean and Final Clean');
insert into category (categoryId, categoryname) values (198, 'Painting & Vinyl Wall Covering');
insert into category (categoryId, categoryname) values (199, 'Site Furnishings');
insert into category (categoryId, categoryname) values (200, 'Masonry & Precast');
insert into category (categoryId, categoryname) values (201, 'HVAC');
insert into category (categoryId, categoryname) values (202, 'Electrical and Fire Alarm');
insert into category (categoryId, categoryname) values (203, 'Electrical');
insert into category (categoryId, categoryname) values (204, 'Prefabricated Aluminum Metal Canopies');
insert into category (categoryId, categoryname) values (205, 'Drywall & Acoustical (FED)');
insert into category (categoryId, categoryname) values (206, 'Framing (Wood)');
insert into category (categoryId, categoryname) values (207, 'Electrical and Fire Alarm');
insert into category (categoryId, categoryname) values (208, 'Fire Protection');
insert into category (categoryId, categoryname) values (209, 'Roofing (Metal)');
insert into category (categoryId, categoryname) values (210, 'Termite Control');
insert into category (categoryId, categoryname) values (211, 'Termite Control');
insert into category (categoryId, categoryname) values (212, 'Roofing (Asphalt)');
insert into category (categoryId, categoryname) values (213, 'Marlite Panels (FED)');
insert into category (categoryId, categoryname) values (214, 'Drilled Shafts');
insert into category (categoryId, categoryname) values (215, 'Rebar & Wire Mesh Install');
insert into category (categoryId, categoryname) values (216, 'Roofing (Asphalt)');
insert into category (categoryId, categoryname) values (217, 'Waterproofing & Caulking');
insert into category (categoryId, categoryname) values (218, 'Fire Protection');
insert into category (categoryId, categoryname) values (219, 'Construction Clean and Final Clean');
insert into category (categoryId, categoryname) values (220, 'Hard Tile & Stone');
insert into category (categoryId, categoryname) values (221, 'HVAC');
insert into category (categoryId, categoryname) values (222, 'Fire Protection');
insert into category (categoryId, categoryname) values (223, 'Electrical and Fire Alarm');
insert into category (categoryId, categoryname) values (224, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (categoryId, categoryname) values (225, 'Hard Tile & Stone');
insert into category (categoryId, categoryname) values (226, 'EIFS');
insert into category (categoryId, categoryname) values (227, 'Glass & Glazing');
insert into category (categoryId, categoryname) values (228, 'Electrical');
insert into category (categoryId, categoryname) values (229, 'Fire Protection');
insert into category (categoryId, categoryname) values (230, 'Overhead Doors');
insert into category (categoryId, categoryname) values (231, 'EIFS');
insert into category (categoryId, categoryname) values (232, 'Drilled Shafts');
insert into category (categoryId, categoryname) values (233, 'Waterproofing & Caulking');
insert into category (categoryId, categoryname) values (234, 'HVAC');
insert into category (categoryId, categoryname) values (235, 'RF Shielding');
insert into category (categoryId, categoryname) values (236, 'HVAC');
insert into category (categoryId, categoryname) values (237, 'Site Furnishings');
insert into category (categoryId, categoryname) values (238, 'Waterproofing & Caulking');
insert into category (categoryId, categoryname) values (239, 'Landscaping & Irrigation');
insert into category (categoryId, categoryname) values (240, 'Overhead Doors');
insert into category (categoryId, categoryname) values (241, 'Structural & Misc Steel Erection');
insert into category (categoryId, categoryname) values (242, 'Structural and Misc Steel (Fabrication)');
insert into category (categoryId, categoryname) values (243, 'Electrical');
insert into category (categoryId, categoryname) values (244, 'Structural & Misc Steel Erection');
insert into category (categoryId, categoryname) values (245, 'Elevator');
insert into category (categoryId, categoryname) values (246, 'Asphalt Paving');
insert into category (categoryId, categoryname) values (247, 'Epoxy Flooring');
insert into category (categoryId, categoryname) values (248, 'Drilled Shafts');
insert into category (categoryId, categoryname) values (249, 'Waterproofing & Caulking');
insert into category (categoryId, categoryname) values (250, 'Wall Protection');
insert into category (categoryId, categoryname) values (251, 'Fire Protection');
insert into category (categoryId, categoryname) values (252, 'Roofing (Metal)');
insert into category (categoryId, categoryname) values (253, 'Hard Tile & Stone');
insert into category (categoryId, categoryname) values (254, 'Granite Surfaces');
insert into category (categoryId, categoryname) values (255, 'Site Furnishings');
insert into category (categoryId, categoryname) values (256, 'Wall Protection');
insert into category (categoryId, categoryname) values (257, 'Framing (Steel)');
insert into category (categoryId, categoryname) values (258, 'Framing (Wood)');
insert into category (categoryId, categoryname) values (259, 'Fire Sprinkler System');
insert into category (categoryId, categoryname) values (260, 'Rebar & Wire Mesh Install');
insert into category (categoryId, categoryname) values (261, 'EIFS');
insert into category (categoryId, categoryname) values (262, 'Site Furnishings');
insert into category (categoryId, categoryname) values (263, 'HVAC');
insert into category (categoryId, categoryname) values (264, 'Casework');
insert into category (categoryId, categoryname) values (265, 'Painting & Vinyl Wall Covering');
insert into category (categoryId, categoryname) values (266, 'Sitework & Site Utilities');
insert into category (categoryId, categoryname) values (267, 'Marlite Panels (FED)');
insert into category (categoryId, categoryname) values (268, 'Casework');
insert into category (categoryId, categoryname) values (269, 'Elevator');
insert into category (categoryId, categoryname) values (270, 'Drywall & Acoustical (MOB)');
insert into category (categoryId, categoryname) values (271, 'Termite Control');
insert into category (categoryId, categoryname) values (272, 'Drywall & Acoustical (FED)');
insert into category (categoryId, categoryname) values (273, 'Masonry & Precast');
insert into category (categoryId, categoryname) values (274, 'Sitework & Site Utilities');
insert into category (categoryId, categoryname) values (275, 'Fire Sprinkler System');
insert into category (categoryId, categoryname) values (276, 'Granite Surfaces');
insert into category (categoryId, categoryname) values (277, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (categoryId, categoryname) values (278, 'Structural & Misc Steel Erection');
insert into category (categoryId, categoryname) values (279, 'Construction Clean and Final Clean');
insert into category (categoryId, categoryname) values (280, 'Drilled Shafts');
insert into category (categoryId, categoryname) values (281, 'Asphalt Paving');
insert into category (categoryId, categoryname) values (282, 'Hard Tile & Stone');
insert into category (categoryId, categoryname) values (283, 'Ornamental Railings');
insert into category (categoryId, categoryname) values (284, 'Granite Surfaces');
insert into category (categoryId, categoryname) values (285, 'Framing (Steel)');
insert into category (categoryId, categoryname) values (286, 'Ornamental Railings');
insert into category (categoryId, categoryname) values (287, 'Ornamental Railings');
insert into category (categoryId, categoryname) values (288, 'HVAC');
insert into category (categoryId, categoryname) values (289, 'Construction Clean and Final Clean');
insert into category (categoryId, categoryname) values (290, 'Drilled Shafts');
insert into category (categoryId, categoryname) values (291, 'Electrical');
insert into category (categoryId, categoryname) values (292, 'Roofing (Metal)');
insert into category (categoryId, categoryname) values (293, 'Masonry & Precast');
insert into category (categoryId, categoryname) values (294, 'Masonry & Precast');
insert into category (categoryId, categoryname) values (295, 'Prefabricated Aluminum Metal Canopies');
insert into category (categoryId, categoryname) values (296, 'Waterproofing & Caulking');
insert into category (categoryId, categoryname) values (297, 'Termite Control');
insert into category (categoryId, categoryname) values (298, 'Roofing (Asphalt)');
insert into category (categoryId, categoryname) values (299, 'Structural & Misc Steel Erection');
insert into category (categoryId, categoryname) values (300, 'Prefabricated Aluminum Metal Canopies');
insert into category (categoryId, categoryname) values (301, 'Retaining Wall and Brick Pavers');
insert into category (categoryId, categoryname) values (302, 'Granite Surfaces');
insert into category (categoryId, categoryname) values (303, 'Structural and Misc Steel (Fabrication)');
insert into category (categoryId, categoryname) values (304, 'Epoxy Flooring');
insert into category (categoryId, categoryname) values (305, 'Granite Surfaces');
insert into category (categoryId, categoryname) values (306, 'Doors, Frames & Hardware');
insert into category (categoryId, categoryname) values (307, 'Rebar & Wire Mesh Install');
insert into category (categoryId, categoryname) values (308, 'Framing (Steel)');
insert into category (categoryId, categoryname) values (309, 'Ornamental Railings');
insert into category (categoryId, categoryname) values (310, 'Retaining Wall and Brick Pavers');
insert into category (categoryId, categoryname) values (311, 'Prefabricated Aluminum Metal Canopies');
insert into category (categoryId, categoryname) values (312, 'Asphalt Paving');
insert into category (categoryId, categoryname) values (313, 'Framing (Wood)');
insert into category (categoryId, categoryname) values (314, 'Prefabricated Aluminum Metal Canopies');
insert into category (categoryId, categoryname) values (315, 'Hard Tile & Stone');
insert into category (categoryId, categoryname) values (316, 'Casework');
insert into category (categoryId, categoryname) values (317, 'Painting & Vinyl Wall Covering');
insert into category (categoryId, categoryname) values (318, 'Waterproofing & Caulking');
insert into category (categoryId, categoryname) values (319, 'Structural & Misc Steel Erection');
insert into category (categoryId, categoryname) values (320, 'Painting & Vinyl Wall Covering');
insert into category (categoryId, categoryname) values (321, 'Electrical');
insert into category (categoryId, categoryname) values (322, 'Fire Sprinkler System');
insert into category (categoryId, categoryname) values (323, 'Soft Flooring and Base');
insert into category (categoryId, categoryname) values (324, 'Structural & Misc Steel Erection');
insert into category (categoryId, categoryname) values (325, 'Electrical and Fire Alarm');
insert into category (categoryId, categoryname) values (326, 'Plumbing & Medical Gas');
insert into category (categoryId, categoryname) values (327, 'Fire Sprinkler System');
insert into category (categoryId, categoryname) values (328, 'Casework');
insert into category (categoryId, categoryname) values (329, 'Framing (Wood)');
insert into category (categoryId, categoryname) values (330, 'Plumbing & Medical Gas');
insert into category (categoryId, categoryname) values (331, 'HVAC');
insert into category (categoryId, categoryname) values (332, 'Masonry & Precast');
insert into category (categoryId, categoryname) values (333, 'Drilled Shafts');
insert into category (categoryId, categoryname) values (334, 'Curb & Gutter');
insert into category (categoryId, categoryname) values (335, 'Glass & Glazing');
insert into category (categoryId, categoryname) values (336, 'Granite Surfaces');
insert into category (categoryId, categoryname) values (337, 'Asphalt Paving');
insert into category (categoryId, categoryname) values (338, 'Asphalt Paving');
insert into category (categoryId, categoryname) values (339, 'Asphalt Paving');
insert into category (categoryId, categoryname) values (340, 'Fire Protection');
insert into category (categoryId, categoryname) values (341, 'Site Furnishings');
insert into category (categoryId, categoryname) values (342, 'Electrical');
insert into category (categoryId, categoryname) values (343, 'Site Furnishings');
insert into category (categoryId, categoryname) values (344, 'Plumbing & Medical Gas');
insert into category (categoryId, categoryname) values (345, 'Rebar & Wire Mesh Install');
insert into category (categoryId, categoryname) values (346, 'Masonry & Precast');
insert into category (categoryId, categoryname) values (347, 'Granite Surfaces');
insert into category (categoryId, categoryname) values (348, 'Electrical');
insert into category (categoryId, categoryname) values (349, 'Plumbing & Medical Gas');
insert into category (categoryId, categoryname) values (350, 'Fire Sprinkler System');
insert into category (categoryId, categoryname) values (351, 'Construction Clean and Final Clean');
insert into category (categoryId, categoryname) values (352, 'Painting & Vinyl Wall Covering');
insert into category (categoryId, categoryname) values (353, 'Epoxy Flooring');
insert into category (categoryId, categoryname) values (354, 'Glass & Glazing');
insert into category (categoryId, categoryname) values (355, 'Framing (Steel)');
insert into category (categoryId, categoryname) values (356, 'Wall Protection');
insert into category (categoryId, categoryname) values (357, 'Structural and Misc Steel (Fabrication)');
insert into category (categoryId, categoryname) values (358, 'Hard Tile & Stone');
insert into category (categoryId, categoryname) values (359, 'Casework');
insert into category (categoryId, categoryname) values (360, 'Retaining Wall and Brick Pavers');
insert into category (categoryId, categoryname) values (361, 'Fire Sprinkler System');
insert into category (categoryId, categoryname) values (362, 'Fire Sprinkler System');
insert into category (categoryId, categoryname) values (363, 'HVAC');
insert into category (categoryId, categoryname) values (364, 'Fire Protection');
insert into category (categoryId, categoryname) values (365, 'Masonry');
insert into category (categoryId, categoryname) values (366, 'Retaining Wall and Brick Pavers');
insert into category (categoryId, categoryname) values (367, 'Electrical and Fire Alarm');
insert into category (categoryId, categoryname) values (368, 'Prefabricated Aluminum Metal Canopies');
insert into category (categoryId, categoryname) values (369, 'Construction Clean and Final Clean');
insert into category (categoryId, categoryname) values (370, 'Structural and Misc Steel (Fabrication)');
insert into category (categoryId, categoryname) values (371, 'Drywall & Acoustical (FED)');
insert into category (categoryId, categoryname) values (372, 'Drywall & Acoustical (FED)');
insert into category (categoryId, categoryname) values (373, 'Roofing (Metal)');
insert into category (categoryId, categoryname) values (374, 'Electrical');
insert into category (categoryId, categoryname) values (375, 'Construction Clean and Final Clean');
insert into category (categoryId, categoryname) values (376, 'Casework');
insert into category (categoryId, categoryname) values (377, 'Fire Protection');
insert into category (categoryId, categoryname) values (378, 'Drywall & Acoustical (FED)');
insert into category (categoryId, categoryname) values (379, 'Overhead Doors');
insert into category (categoryId, categoryname) values (380, 'Soft Flooring and Base');
insert into category (categoryId, categoryname) values (381, 'Overhead Doors');
insert into category (categoryId, categoryname) values (382, 'EIFS');
insert into category (categoryId, categoryname) values (383, 'Waterproofing & Caulking');
insert into category (categoryId, categoryname) values (384, 'Structural and Misc Steel (Fabrication)');
insert into category (categoryId, categoryname) values (385, 'Fire Protection');
insert into category (categoryId, categoryname) values (386, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (categoryId, categoryname) values (387, 'Retaining Wall and Brick Pavers');
insert into category (categoryId, categoryname) values (388, 'Hard Tile & Stone');
insert into category (categoryId, categoryname) values (389, 'Masonry');
insert into category (categoryId, categoryname) values (390, 'Casework');
insert into category (categoryId, categoryname) values (391, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (categoryId, categoryname) values (392, 'Wall Protection');
insert into category (categoryId, categoryname) values (393, 'Exterior Signage');
insert into category (categoryId, categoryname) values (394, 'Wall Protection');
insert into category (categoryId, categoryname) values (395, 'RF Shielding');
insert into category (categoryId, categoryname) values (396, 'Construction Clean and Final Clean');
insert into category (categoryId, categoryname) values (397, 'Roofing (Metal)');
insert into category (categoryId, categoryname) values (398, 'Casework');
insert into category (categoryId, categoryname) values (399, 'Electrical');
insert into category (categoryId, categoryname) values (400, 'Landscaping & Irrigation');
insert into category (categoryId, categoryname) values (401, 'Electrical and Fire Alarm');
insert into category (categoryId, categoryname) values (402, 'Masonry');
insert into category (categoryId, categoryname) values (403, 'Fire Sprinkler System');
insert into category (categoryId, categoryname) values (404, 'Site Furnishings');
insert into category (categoryId, categoryname) values (405, 'Soft Flooring and Base');
insert into category (categoryId, categoryname) values (406, 'Epoxy Flooring');
insert into category (categoryId, categoryname) values (407, 'Plumbing & Medical Gas');
insert into category (categoryId, categoryname) values (408, 'Drywall & Acoustical (FED)');
insert into category (categoryId, categoryname) values (409, 'Roofing (Asphalt)');
insert into category (categoryId, categoryname) values (410, 'Ornamental Railings');
insert into category (categoryId, categoryname) values (411, 'Fire Sprinkler System');
insert into category (categoryId, categoryname) values (412, 'HVAC');
insert into category (categoryId, categoryname) values (413, 'Doors, Frames & Hardware');
insert into category (categoryId, categoryname) values (414, 'Exterior Signage');
insert into category (categoryId, categoryname) values (415, 'Ornamental Railings');
insert into category (categoryId, categoryname) values (416, 'Granite Surfaces');
insert into category (categoryId, categoryname) values (417, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (categoryId, categoryname) values (418, 'Soft Flooring and Base');
insert into category (categoryId, categoryname) values (419, 'Painting & Vinyl Wall Covering');
insert into category (categoryId, categoryname) values (420, 'Framing (Steel)');
insert into category (categoryId, categoryname) values (421, 'Wall Protection');
insert into category (categoryId, categoryname) values (422, 'Landscaping & Irrigation');
insert into category (categoryId, categoryname) values (423, 'Exterior Signage');
insert into category (categoryId, categoryname) values (424, 'Roofing (Asphalt)');
insert into category (categoryId, categoryname) values (425, 'Prefabricated Aluminum Metal Canopies');
insert into category (categoryId, categoryname) values (426, 'Drilled Shafts');
insert into category (categoryId, categoryname) values (427, 'Framing (Steel)');
insert into category (categoryId, categoryname) values (428, 'Landscaping & Irrigation');
insert into category (categoryId, categoryname) values (429, 'Epoxy Flooring');
insert into category (categoryId, categoryname) values (430, 'Rebar & Wire Mesh Install');
insert into category (categoryId, categoryname) values (431, 'Fire Sprinkler System');
insert into category (categoryId, categoryname) values (432, 'Exterior Signage');
insert into category (categoryId, categoryname) values (433, 'Drywall & Acoustical (FED)');
insert into category (categoryId, categoryname) values (434, 'Doors, Frames & Hardware');
insert into category (categoryId, categoryname) values (435, 'Electrical');
insert into category (categoryId, categoryname) values (436, 'Granite Surfaces');
insert into category (categoryId, categoryname) values (437, 'Landscaping & Irrigation');
insert into category (categoryId, categoryname) values (438, 'Overhead Doors');
insert into category (categoryId, categoryname) values (439, 'Structural and Misc Steel (Fabrication)');
insert into category (categoryId, categoryname) values (440, 'Overhead Doors');
insert into category (categoryId, categoryname) values (441, 'Asphalt Paving');
insert into category (categoryId, categoryname) values (442, 'Landscaping & Irrigation');
insert into category (categoryId, categoryname) values (443, 'Exterior Signage');
insert into category (categoryId, categoryname) values (444, 'Site Furnishings');
insert into category (categoryId, categoryname) values (445, 'Electrical');
insert into category (categoryId, categoryname) values (446, 'Elevator');
insert into category (categoryId, categoryname) values (447, 'HVAC');
insert into category (categoryId, categoryname) values (448, 'Electrical');
insert into category (categoryId, categoryname) values (449, 'Waterproofing & Caulking');
insert into category (categoryId, categoryname) values (450, 'Fire Protection');
insert into category (categoryId, categoryname) values (451, 'Structural and Misc Steel (Fabrication)');
insert into category (categoryId, categoryname) values (452, 'Structural & Misc Steel Erection');
insert into category (categoryId, categoryname) values (453, 'Elevator');
insert into category (categoryId, categoryname) values (454, 'Structural and Misc Steel (Fabrication)');
insert into category (categoryId, categoryname) values (455, 'Framing (Steel)');
insert into category (categoryId, categoryname) values (456, 'Fire Sprinkler System');
insert into category (categoryId, categoryname) values (457, 'Masonry & Precast');
insert into category (categoryId, categoryname) values (458, 'Waterproofing & Caulking');
insert into category (categoryId, categoryname) values (459, 'Drywall & Acoustical (FED)');
insert into category (categoryId, categoryname) values (460, 'Soft Flooring and Base');
insert into category (categoryId, categoryname) values (461, 'Site Furnishings');
insert into category (categoryId, categoryname) values (462, 'Plumbing & Medical Gas');
insert into category (categoryId, categoryname) values (463, 'Glass & Glazing');
insert into category (categoryId, categoryname) values (464, 'Painting & Vinyl Wall Covering');
insert into category (categoryId, categoryname) values (465, 'Asphalt Paving');
insert into category (categoryId, categoryname) values (466, 'Soft Flooring and Base');
insert into category (categoryId, categoryname) values (467, 'Landscaping & Irrigation');
insert into category (categoryId, categoryname) values (468, 'Fire Protection');
insert into category (categoryId, categoryname) values (469, 'Landscaping & Irrigation');
insert into category (categoryId, categoryname) values (470, 'Rebar & Wire Mesh Install');
insert into category (categoryId, categoryname) values (471, 'Fire Sprinkler System');
insert into category (categoryId, categoryname) values (472, 'Drilled Shafts');
insert into category (categoryId, categoryname) values (473, 'Marlite Panels (FED)');
insert into category (categoryId, categoryname) values (474, 'Granite Surfaces');
insert into category (categoryId, categoryname) values (475, 'Structural and Misc Steel (Fabrication)');
insert into category (categoryId, categoryname) values (476, 'Fire Sprinkler System');
insert into category (categoryId, categoryname) values (477, 'Curb & Gutter');
insert into category (categoryId, categoryname) values (478, 'Masonry');
insert into category (categoryId, categoryname) values (479, 'Fire Sprinkler System');
insert into category (categoryId, categoryname) values (480, 'Waterproofing & Caulking');
insert into category (categoryId, categoryname) values (481, 'Structural & Misc Steel Erection');
insert into category (categoryId, categoryname) values (482, 'Roofing (Metal)');
insert into category (categoryId, categoryname) values (483, 'Electrical and Fire Alarm');
insert into category (categoryId, categoryname) values (484, 'HVAC');
insert into category (categoryId, categoryname) values (485, 'Landscaping & Irrigation');
insert into category (categoryId, categoryname) values (486, 'Framing (Steel)');
insert into category (categoryId, categoryname) values (487, 'Framing (Steel)');
insert into category (categoryId, categoryname) values (488, 'Drywall & Acoustical (FED)');
insert into category (categoryId, categoryname) values (489, 'Ornamental Railings');
insert into category (categoryId, categoryname) values (490, 'Framing (Steel)');
insert into category (categoryId, categoryname) values (491, 'Construction Clean and Final Clean');
insert into category (categoryId, categoryname) values (492, 'Doors, Frames & Hardware');
insert into category (categoryId, categoryname) values (493, 'EIFS');
insert into category (categoryId, categoryname) values (494, 'Retaining Wall and Brick Pavers');
insert into category (categoryId, categoryname) values (495, 'Roofing (Asphalt)');
insert into category (categoryId, categoryname) values (496, 'Framing (Steel)');
insert into category (categoryId, categoryname) values (497, 'Fire Sprinkler System');
insert into category (categoryId, categoryname) values (498, 'Ornamental Railings');
insert into category (categoryId, categoryname) values (499, 'Elevator');
insert into category (categoryId, categoryname) values (500, 'Hard Tile & Stone');
insert into category (categoryId, categoryname) values (501, 'Doors, Frames & Hardware');
insert into category (categoryId, categoryname) values (502, 'Termite Control');
insert into category (categoryId, categoryname) values (503, 'Framing (Steel)');
insert into category (categoryId, categoryname) values (504, 'Curb & Gutter');
insert into category (categoryId, categoryname) values (505, 'Overhead Doors');
insert into category (categoryId, categoryname) values (506, 'Soft Flooring and Base');
insert into category (categoryId, categoryname) values (507, 'Marlite Panels (FED)');
insert into category (categoryId, categoryname) values (508, 'Construction Clean and Final Clean');
insert into category (categoryId, categoryname) values (509, 'Fire Sprinkler System');
insert into category (categoryId, categoryname) values (510, 'Electrical');
insert into category (categoryId, categoryname) values (511, 'Elevator');
insert into category (categoryId, categoryname) values (512, 'Drilled Shafts');
insert into category (categoryId, categoryname) values (513, 'Soft Flooring and Base');
insert into category (categoryId, categoryname) values (514, 'Electrical and Fire Alarm');
insert into category (categoryId, categoryname) values (515, 'Framing (Wood)');
insert into category (categoryId, categoryname) values (516, 'Framing (Wood)');
insert into category (categoryId, categoryname) values (517, 'Casework');
insert into category (categoryId, categoryname) values (518, 'Sitework & Site Utilities');
insert into category (categoryId, categoryname) values (519, 'Epoxy Flooring');
insert into category (categoryId, categoryname) values (520, 'Masonry');
insert into category (categoryId, categoryname) values (521, 'Drilled Shafts');
insert into category (categoryId, categoryname) values (522, 'Framing (Steel)');
insert into category (categoryId, categoryname) values (523, 'Landscaping & Irrigation');
insert into category (categoryId, categoryname) values (524, 'Granite Surfaces');
insert into category (categoryId, categoryname) values (525, 'EIFS');
insert into category (categoryId, categoryname) values (526, 'Retaining Wall and Brick Pavers');
insert into category (categoryId, categoryname) values (527, 'Fire Sprinkler System');
insert into category (categoryId, categoryname) values (528, 'Roofing (Asphalt)');
insert into category (categoryId, categoryname) values (529, 'Structural and Misc Steel (Fabrication)');
insert into category (categoryId, categoryname) values (530, 'Prefabricated Aluminum Metal Canopies');
insert into category (categoryId, categoryname) values (531, 'Site Furnishings');
insert into category (categoryId, categoryname) values (532, 'Drywall & Acoustical (FED)');
insert into category (categoryId, categoryname) values (533, 'Prefabricated Aluminum Metal Canopies');
insert into category (categoryId, categoryname) values (534, 'Plumbing & Medical Gas');
insert into category (categoryId, categoryname) values (535, 'Plumbing & Medical Gas');
insert into category (categoryId, categoryname) values (536, 'Electrical and Fire Alarm');
insert into category (categoryId, categoryname) values (537, 'Hard Tile & Stone');
insert into category (categoryId, categoryname) values (538, 'Asphalt Paving');
insert into category (categoryId, categoryname) values (539, 'Elevator');
insert into category (categoryId, categoryname) values (540, 'Retaining Wall and Brick Pavers');
insert into category (categoryId, categoryname) values (541, 'Casework');
insert into category (categoryId, categoryname) values (542, 'Construction Clean and Final Clean');
insert into category (categoryId, categoryname) values (543, 'Soft Flooring and Base');
insert into category (categoryId, categoryname) values (544, 'Rebar & Wire Mesh Install');
insert into category (categoryId, categoryname) values (545, 'Framing (Wood)');
insert into category (categoryId, categoryname) values (546, 'Granite Surfaces');
insert into category (categoryId, categoryname) values (547, 'Roofing (Asphalt)');
insert into category (categoryId, categoryname) values (548, 'Framing (Wood)');
insert into category (categoryId, categoryname) values (549, 'Hard Tile & Stone');
insert into category (categoryId, categoryname) values (550, 'Termite Control');
insert into category (categoryId, categoryname) values (551, 'Retaining Wall and Brick Pavers');
insert into category (categoryId, categoryname) values (552, 'Soft Flooring and Base');
insert into category (categoryId, categoryname) values (553, 'Fire Protection');
insert into category (categoryId, categoryname) values (554, 'Painting & Vinyl Wall Covering');
insert into category (categoryId, categoryname) values (555, 'Electrical and Fire Alarm');
insert into category (categoryId, categoryname) values (556, 'Framing (Wood)');
insert into category (categoryId, categoryname) values (557, 'Curb & Gutter');
insert into category (categoryId, categoryname) values (558, 'Hard Tile & Stone');
insert into category (categoryId, categoryname) values (559, 'Waterproofing & Caulking');
insert into category (categoryId, categoryname) values (560, 'Prefabricated Aluminum Metal Canopies');
insert into category (categoryId, categoryname) values (561, 'Retaining Wall and Brick Pavers');
insert into category (categoryId, categoryname) values (562, 'Retaining Wall and Brick Pavers');
insert into category (categoryId, categoryname) values (563, 'HVAC');
insert into category (categoryId, categoryname) values (564, 'Granite Surfaces');
insert into category (categoryId, categoryname) values (565, 'Plumbing & Medical Gas');
insert into category (categoryId, categoryname) values (566, 'Overhead Doors');
insert into category (categoryId, categoryname) values (567, 'Rebar & Wire Mesh Install');
insert into category (categoryId, categoryname) values (568, 'Electrical and Fire Alarm');
insert into category (categoryId, categoryname) values (569, 'Elevator');
insert into category (categoryId, categoryname) values (570, 'Marlite Panels (FED)');
insert into category (categoryId, categoryname) values (571, 'Masonry & Precast');
insert into category (categoryId, categoryname) values (572, 'Elevator');
insert into category (categoryId, categoryname) values (573, 'Plumbing & Medical Gas');
insert into category (categoryId, categoryname) values (574, 'Drywall & Acoustical (FED)');
insert into category (categoryId, categoryname) values (575, 'Retaining Wall and Brick Pavers');
insert into category (categoryId, categoryname) values (576, 'Marlite Panels (FED)');
insert into category (categoryId, categoryname) values (577, 'Plumbing & Medical Gas');
insert into category (categoryId, categoryname) values (578, 'Drywall & Acoustical (FED)');
insert into category (categoryId, categoryname) values (579, 'Drywall & Acoustical (MOB)');
insert into category (categoryId, categoryname) values (580, 'Roofing (Asphalt)');
insert into category (categoryId, categoryname) values (581, 'Glass & Glazing');
insert into category (categoryId, categoryname) values (582, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (categoryId, categoryname) values (583, 'Wall Protection');
insert into category (categoryId, categoryname) values (584, 'Doors, Frames & Hardware');
insert into category (categoryId, categoryname) values (585, 'Framing (Steel)');
insert into category (categoryId, categoryname) values (586, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (categoryId, categoryname) values (587, 'Doors, Frames & Hardware');
insert into category (categoryId, categoryname) values (588, 'Electrical and Fire Alarm');
insert into category (categoryId, categoryname) values (589, 'Prefabricated Aluminum Metal Canopies');
insert into category (categoryId, categoryname) values (590, 'Ornamental Railings');
insert into category (categoryId, categoryname) values (591, 'Masonry & Precast');
insert into category (categoryId, categoryname) values (592, 'HVAC');
insert into category (categoryId, categoryname) values (593, 'Roofing (Asphalt)');
insert into category (categoryId, categoryname) values (594, 'Wall Protection');
insert into category (categoryId, categoryname) values (595, 'HVAC');
insert into category (categoryId, categoryname) values (596, 'Drywall & Acoustical (MOB)');
insert into category (categoryId, categoryname) values (597, 'Prefabricated Aluminum Metal Canopies');
insert into category (categoryId, categoryname) values (598, 'Framing (Steel)');
insert into category (categoryId, categoryname) values (599, 'Sitework & Site Utilities');
insert into category (categoryId, categoryname) values (600, 'Doors, Frames & Hardware');
insert into category (categoryId, categoryname) values (601, 'Hard Tile & Stone');
insert into category (categoryId, categoryname) values (602, 'Electrical');
insert into category (categoryId, categoryname) values (603, 'Epoxy Flooring');
insert into category (categoryId, categoryname) values (604, 'Sitework & Site Utilities');
insert into category (categoryId, categoryname) values (605, 'Drilled Shafts');
insert into category (categoryId, categoryname) values (606, 'Masonry & Precast');
insert into category (categoryId, categoryname) values (607, 'Granite Surfaces');
insert into category (categoryId, categoryname) values (608, 'Prefabricated Aluminum Metal Canopies');
insert into category (categoryId, categoryname) values (609, 'Site Furnishings');
insert into category (categoryId, categoryname) values (610, 'Framing (Wood)');
insert into category (categoryId, categoryname) values (611, 'Exterior Signage');
insert into category (categoryId, categoryname) values (612, 'Hard Tile & Stone');
insert into category (categoryId, categoryname) values (613, 'Fire Sprinkler System');
insert into category (categoryId, categoryname) values (614, 'Structural and Misc Steel (Fabrication)');
insert into category (categoryId, categoryname) values (615, 'Drywall & Acoustical (FED)');
insert into category (categoryId, categoryname) values (616, 'Painting & Vinyl Wall Covering');
insert into category (categoryId, categoryname) values (617, 'Construction Clean and Final Clean');
insert into category (categoryId, categoryname) values (618, 'Drilled Shafts');
insert into category (categoryId, categoryname) values (619, 'Electrical');
insert into category (categoryId, categoryname) values (620, 'Granite Surfaces');
insert into category (categoryId, categoryname) values (621, 'Plumbing & Medical Gas');
insert into category (categoryId, categoryname) values (622, 'Sitework & Site Utilities');
insert into category (categoryId, categoryname) values (623, 'Casework');
insert into category (categoryId, categoryname) values (624, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (categoryId, categoryname) values (625, 'Asphalt Paving');
insert into category (categoryId, categoryname) values (626, 'Framing (Steel)');
insert into category (categoryId, categoryname) values (627, 'Retaining Wall and Brick Pavers');
insert into category (categoryId, categoryname) values (628, 'Ornamental Railings');
insert into category (categoryId, categoryname) values (629, 'Masonry');
insert into category (categoryId, categoryname) values (630, 'Glass & Glazing');
insert into category (categoryId, categoryname) values (631, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (categoryId, categoryname) values (632, 'Masonry');
insert into category (categoryId, categoryname) values (633, 'Epoxy Flooring');
insert into category (categoryId, categoryname) values (634, 'Wall Protection');
insert into category (categoryId, categoryname) values (635, 'Glass & Glazing');
insert into category (categoryId, categoryname) values (636, 'Hard Tile & Stone');
insert into category (categoryId, categoryname) values (637, 'Roofing (Metal)');
insert into category (categoryId, categoryname) values (638, 'Casework');
insert into category (categoryId, categoryname) values (639, 'RF Shielding');
insert into category (categoryId, categoryname) values (640, 'Marlite Panels (FED)');
insert into category (categoryId, categoryname) values (641, 'Waterproofing & Caulking');
insert into category (categoryId, categoryname) values (642, 'Doors, Frames & Hardware');
insert into category (categoryId, categoryname) values (643, 'Curb & Gutter');
insert into category (categoryId, categoryname) values (644, 'Soft Flooring and Base');
insert into category (categoryId, categoryname) values (645, 'Site Furnishings');
insert into category (categoryId, categoryname) values (646, 'Hard Tile & Stone');
insert into category (categoryId, categoryname) values (647, 'Drilled Shafts');
insert into category (categoryId, categoryname) values (648, 'Roofing (Metal)');
insert into category (categoryId, categoryname) values (649, 'Epoxy Flooring');
insert into category (categoryId, categoryname) values (650, 'Fire Sprinkler System');
insert into category (categoryId, categoryname) values (651, 'Framing (Steel)');
insert into category (categoryId, categoryname) values (652, 'Doors, Frames & Hardware');
insert into category (categoryId, categoryname) values (653, 'Granite Surfaces');
insert into category (categoryId, categoryname) values (654, 'Casework');
insert into category (categoryId, categoryname) values (655, 'Framing (Wood)');
insert into category (categoryId, categoryname) values (656, 'Plumbing & Medical Gas');
insert into category (categoryId, categoryname) values (657, 'EIFS');
insert into category (categoryId, categoryname) values (658, 'Sitework & Site Utilities');
insert into category (categoryId, categoryname) values (659, 'Landscaping & Irrigation');
insert into category (categoryId, categoryname) values (660, 'Rebar & Wire Mesh Install');
insert into category (categoryId, categoryname) values (661, 'RF Shielding');
insert into category (categoryId, categoryname) values (662, 'Casework');
insert into category (categoryId, categoryname) values (663, 'Drywall & Acoustical (FED)');
insert into category (categoryId, categoryname) values (664, 'Granite Surfaces');
insert into category (categoryId, categoryname) values (665, 'Granite Surfaces');
insert into category (categoryId, categoryname) values (666, 'HVAC');
insert into category (categoryId, categoryname) values (667, 'Masonry & Precast');
insert into category (categoryId, categoryname) values (668, 'Landscaping & Irrigation');
insert into category (categoryId, categoryname) values (669, 'Granite Surfaces');
insert into category (categoryId, categoryname) values (670, 'Masonry');
insert into category (categoryId, categoryname) values (671, 'Painting & Vinyl Wall Covering');
insert into category (categoryId, categoryname) values (672, 'Wall Protection');
insert into category (categoryId, categoryname) values (673, 'Prefabricated Aluminum Metal Canopies');
insert into category (categoryId, categoryname) values (674, 'Doors, Frames & Hardware');
insert into category (categoryId, categoryname) values (675, 'Curb & Gutter');
insert into category (categoryId, categoryname) values (676, 'Construction Clean and Final Clean');
insert into category (categoryId, categoryname) values (677, 'EIFS');
insert into category (categoryId, categoryname) values (678, 'Sitework & Site Utilities');
insert into category (categoryId, categoryname) values (679, 'Prefabricated Aluminum Metal Canopies');
insert into category (categoryId, categoryname) values (680, 'Drywall & Acoustical (FED)');
insert into category (categoryId, categoryname) values (681, 'Sitework & Site Utilities');
insert into category (categoryId, categoryname) values (682, 'Roofing (Metal)');
insert into category (categoryId, categoryname) values (683, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (categoryId, categoryname) values (684, 'Fire Protection');
insert into category (categoryId, categoryname) values (685, 'Wall Protection');
insert into category (categoryId, categoryname) values (686, 'Framing (Steel)');
insert into category (categoryId, categoryname) values (687, 'Masonry');
insert into category (categoryId, categoryname) values (688, 'Prefabricated Aluminum Metal Canopies');
insert into category (categoryId, categoryname) values (689, 'Waterproofing & Caulking');
insert into category (categoryId, categoryname) values (690, 'Asphalt Paving');
insert into category (categoryId, categoryname) values (691, 'Construction Clean and Final Clean');
insert into category (categoryId, categoryname) values (692, 'Landscaping & Irrigation');
insert into category (categoryId, categoryname) values (693, 'Roofing (Metal)');
insert into category (categoryId, categoryname) values (694, 'EIFS');
insert into category (categoryId, categoryname) values (695, 'Asphalt Paving');
insert into category (categoryId, categoryname) values (696, 'Drywall & Acoustical (MOB)');
insert into category (categoryId, categoryname) values (697, 'Exterior Signage');
insert into category (categoryId, categoryname) values (698, 'Soft Flooring and Base');
insert into category (categoryId, categoryname) values (699, 'Masonry & Precast');
insert into category (categoryId, categoryname) values (700, 'Retaining Wall and Brick Pavers');
insert into category (categoryId, categoryname) values (701, 'Marlite Panels (FED)');
insert into category (categoryId, categoryname) values (702, 'Painting & Vinyl Wall Covering');
insert into category (categoryId, categoryname) values (703, 'Drywall & Acoustical (MOB)');
insert into category (categoryId, categoryname) values (704, 'Waterproofing & Caulking');
insert into category (categoryId, categoryname) values (705, 'Wall Protection');
insert into category (categoryId, categoryname) values (706, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (categoryId, categoryname) values (707, 'Sitework & Site Utilities');
insert into category (categoryId, categoryname) values (708, 'Wall Protection');
insert into category (categoryId, categoryname) values (709, 'Exterior Signage');
insert into category (categoryId, categoryname) values (710, 'Landscaping & Irrigation');
insert into category (categoryId, categoryname) values (711, 'Framing (Wood)');
insert into category (categoryId, categoryname) values (712, 'Curb & Gutter');
insert into category (categoryId, categoryname) values (713, 'Fire Protection');
insert into category (categoryId, categoryname) values (714, 'Drywall & Acoustical (FED)');
insert into category (categoryId, categoryname) values (715, 'Termite Control');
insert into category (categoryId, categoryname) values (716, 'Masonry & Precast');
insert into category (categoryId, categoryname) values (717, 'Drywall & Acoustical (MOB)');
insert into category (categoryId, categoryname) values (718, 'Framing (Steel)');
insert into category (categoryId, categoryname) values (719, 'Framing (Steel)');
insert into category (categoryId, categoryname) values (720, 'Electrical');
insert into category (categoryId, categoryname) values (721, 'Roofing (Asphalt)');
insert into category (categoryId, categoryname) values (722, 'Framing (Steel)');
insert into category (categoryId, categoryname) values (723, 'Masonry');
insert into category (categoryId, categoryname) values (724, 'Exterior Signage');
insert into category (categoryId, categoryname) values (725, 'Casework');
insert into category (categoryId, categoryname) values (726, 'Granite Surfaces');
insert into category (categoryId, categoryname) values (727, 'Casework');
insert into category (categoryId, categoryname) values (728, 'Granite Surfaces');
insert into category (categoryId, categoryname) values (729, 'Construction Clean and Final Clean');
insert into category (categoryId, categoryname) values (730, 'RF Shielding');
insert into category (categoryId, categoryname) values (731, 'Site Furnishings');
insert into category (categoryId, categoryname) values (732, 'Masonry & Precast');
insert into category (categoryId, categoryname) values (733, 'Glass & Glazing');
insert into category (categoryId, categoryname) values (734, 'Drilled Shafts');
insert into category (categoryId, categoryname) values (735, 'Sitework & Site Utilities');
insert into category (categoryId, categoryname) values (736, 'Doors, Frames & Hardware');
insert into category (categoryId, categoryname) values (737, 'Casework');
insert into category (categoryId, categoryname) values (738, 'Landscaping & Irrigation');
insert into category (categoryId, categoryname) values (739, 'Curb & Gutter');
insert into category (categoryId, categoryname) values (740, 'Landscaping & Irrigation');
insert into category (categoryId, categoryname) values (741, 'Drywall & Acoustical (FED)');
insert into category (categoryId, categoryname) values (742, 'Landscaping & Irrigation');
insert into category (categoryId, categoryname) values (743, 'Asphalt Paving');
insert into category (categoryId, categoryname) values (744, 'Doors, Frames & Hardware');
insert into category (categoryId, categoryname) values (745, 'Casework');
insert into category (categoryId, categoryname) values (746, 'Elevator');
insert into category (categoryId, categoryname) values (747, 'Sitework & Site Utilities');
insert into category (categoryId, categoryname) values (748, 'Soft Flooring and Base');
insert into category (categoryId, categoryname) values (749, 'Site Furnishings');
insert into category (categoryId, categoryname) values (750, 'HVAC');
insert into category (categoryId, categoryname) values (751, 'Masonry & Precast');
insert into category (categoryId, categoryname) values (752, 'Waterproofing & Caulking');
insert into category (categoryId, categoryname) values (753, 'Wall Protection');
insert into category (categoryId, categoryname) values (754, 'Elevator');
insert into category (categoryId, categoryname) values (755, 'Overhead Doors');
insert into category (categoryId, categoryname) values (756, 'Masonry');
insert into category (categoryId, categoryname) values (757, 'Wall Protection');
insert into category (categoryId, categoryname) values (758, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (categoryId, categoryname) values (759, 'HVAC');
insert into category (categoryId, categoryname) values (760, 'Marlite Panels (FED)');
insert into category (categoryId, categoryname) values (761, 'Electrical and Fire Alarm');
insert into category (categoryId, categoryname) values (762, 'Framing (Steel)');
insert into category (categoryId, categoryname) values (763, 'EIFS');
insert into category (categoryId, categoryname) values (764, 'Marlite Panels (FED)');
insert into category (categoryId, categoryname) values (765, 'HVAC');
insert into category (categoryId, categoryname) values (766, 'Glass & Glazing');
insert into category (categoryId, categoryname) values (767, 'Doors, Frames & Hardware');
insert into category (categoryId, categoryname) values (768, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (categoryId, categoryname) values (769, 'Doors, Frames & Hardware');
insert into category (categoryId, categoryname) values (770, 'Prefabricated Aluminum Metal Canopies');
insert into category (categoryId, categoryname) values (771, 'Granite Surfaces');
insert into category (categoryId, categoryname) values (772, 'Glass & Glazing');
insert into category (categoryId, categoryname) values (773, 'Plumbing & Medical Gas');
insert into category (categoryId, categoryname) values (774, 'Prefabricated Aluminum Metal Canopies');
insert into category (categoryId, categoryname) values (775, 'Retaining Wall and Brick Pavers');
insert into category (categoryId, categoryname) values (776, 'Ornamental Railings');
insert into category (categoryId, categoryname) values (777, 'Wall Protection');
insert into category (categoryId, categoryname) values (778, 'Casework');
insert into category (categoryId, categoryname) values (779, 'Fire Protection');
insert into category (categoryId, categoryname) values (780, 'Electrical');
insert into category (categoryId, categoryname) values (781, 'Roofing (Metal)');
insert into category (categoryId, categoryname) values (782, 'Prefabricated Aluminum Metal Canopies');
insert into category (categoryId, categoryname) values (783, 'Electrical');
insert into category (categoryId, categoryname) values (784, 'Rebar & Wire Mesh Install');
insert into category (categoryId, categoryname) values (785, 'Painting & Vinyl Wall Covering');
insert into category (categoryId, categoryname) values (786, 'Site Furnishings');
insert into category (categoryId, categoryname) values (787, 'Construction Clean and Final Clean');
insert into category (categoryId, categoryname) values (788, 'Wall Protection');
insert into category (categoryId, categoryname) values (789, 'Granite Surfaces');
insert into category (categoryId, categoryname) values (790, 'Elevator');
insert into category (categoryId, categoryname) values (791, 'Electrical');
insert into category (categoryId, categoryname) values (792, 'Drywall & Acoustical (MOB)');
insert into category (categoryId, categoryname) values (793, 'Electrical');
insert into category (categoryId, categoryname) values (794, 'Marlite Panels (FED)');
insert into category (categoryId, categoryname) values (795, 'Doors, Frames & Hardware');
insert into category (categoryId, categoryname) values (796, 'Curb & Gutter');
insert into category (categoryId, categoryname) values (797, 'Drywall & Acoustical (FED)');
insert into category (categoryId, categoryname) values (798, 'Painting & Vinyl Wall Covering');
insert into category (categoryId, categoryname) values (799, 'RF Shielding');
insert into category (categoryId, categoryname) values (800, 'Soft Flooring and Base');
insert into category (categoryId, categoryname) values (801, 'Elevator');
insert into category (categoryId, categoryname) values (802, 'Retaining Wall and Brick Pavers');
insert into category (categoryId, categoryname) values (803, 'Soft Flooring and Base');
insert into category (categoryId, categoryname) values (804, 'Fire Sprinkler System');
insert into category (categoryId, categoryname) values (805, 'Epoxy Flooring');
insert into category (categoryId, categoryname) values (806, 'Fire Protection');
insert into category (categoryId, categoryname) values (807, 'Rebar & Wire Mesh Install');
insert into category (categoryId, categoryname) values (808, 'Exterior Signage');
insert into category (categoryId, categoryname) values (809, 'Electrical');
insert into category (categoryId, categoryname) values (810, 'Soft Flooring and Base');
insert into category (categoryId, categoryname) values (811, 'Landscaping & Irrigation');
insert into category (categoryId, categoryname) values (812, 'Granite Surfaces');
insert into category (categoryId, categoryname) values (813, 'Construction Clean and Final Clean');
insert into category (categoryId, categoryname) values (814, 'Glass & Glazing');
insert into category (categoryId, categoryname) values (815, 'Retaining Wall and Brick Pavers');
insert into category (categoryId, categoryname) values (816, 'Masonry & Precast');
insert into category (categoryId, categoryname) values (817, 'Fire Protection');
insert into category (categoryId, categoryname) values (818, 'Drywall & Acoustical (MOB)');
insert into category (categoryId, categoryname) values (819, 'Fire Sprinkler System');
insert into category (categoryId, categoryname) values (820, 'Drilled Shafts');
insert into category (categoryId, categoryname) values (821, 'Curb & Gutter');
insert into category (categoryId, categoryname) values (822, 'Roofing (Asphalt)');
insert into category (categoryId, categoryname) values (823, 'Painting & Vinyl Wall Covering');
insert into category (categoryId, categoryname) values (824, 'Asphalt Paving');
insert into category (categoryId, categoryname) values (825, 'Doors, Frames & Hardware');
insert into category (categoryId, categoryname) values (826, 'Marlite Panels (FED)');
insert into category (categoryId, categoryname) values (827, 'Drywall & Acoustical (FED)');
insert into category (categoryId, categoryname) values (828, 'Exterior Signage');
insert into category (categoryId, categoryname) values (829, 'Marlite Panels (FED)');
insert into category (categoryId, categoryname) values (830, 'Sitework & Site Utilities');
insert into category (categoryId, categoryname) values (831, 'Soft Flooring and Base');
insert into category (categoryId, categoryname) values (832, 'Electrical and Fire Alarm');
insert into category (categoryId, categoryname) values (833, 'Fire Sprinkler System');
insert into category (categoryId, categoryname) values (834, 'Soft Flooring and Base');
insert into category (categoryId, categoryname) values (835, 'Site Furnishings');
insert into category (categoryId, categoryname) values (836, 'Exterior Signage');
insert into category (categoryId, categoryname) values (837, 'Drywall & Acoustical (FED)');
insert into category (categoryId, categoryname) values (838, 'Structural and Misc Steel (Fabrication)');
insert into category (categoryId, categoryname) values (839, 'Doors, Frames & Hardware');
insert into category (categoryId, categoryname) values (840, 'Fire Protection');
insert into category (categoryId, categoryname) values (841, 'Electrical and Fire Alarm');
insert into category (categoryId, categoryname) values (842, 'Electrical');
insert into category (categoryId, categoryname) values (843, 'Doors, Frames & Hardware');
insert into category (categoryId, categoryname) values (844, 'Hard Tile & Stone');
insert into category (categoryId, categoryname) values (845, 'Site Furnishings');
insert into category (categoryId, categoryname) values (846, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (categoryId, categoryname) values (847, 'Roofing (Asphalt)');
insert into category (categoryId, categoryname) values (848, 'Hard Tile & Stone');
insert into category (categoryId, categoryname) values (849, 'Painting & Vinyl Wall Covering');
insert into category (categoryId, categoryname) values (850, 'Casework');
insert into category (categoryId, categoryname) values (851, 'Temp Fencing, Decorative Fencing and Gates');
insert into category (categoryId, categoryname) values (852, 'Glass & Glazing');
insert into category (categoryId, categoryname) values (853, 'Masonry');
insert into category (categoryId, categoryname) values (854, 'Fire Sprinkler System');
insert into category (categoryId, categoryname) values (855, 'Drywall & Acoustical (MOB)');
insert into category (categoryId, categoryname) values (856, 'Prefabricated Aluminum Metal Canopies');
insert into category (categoryId, categoryname) values (857, 'Drilled Shafts');
insert into category (categoryId, categoryname) values (858, 'Termite Control');
insert into category (categoryId, categoryname) values (859, 'Drywall & Acoustical (MOB)');
insert into category (categoryId, categoryname) values (860, 'Marlite Panels (FED)');
insert into category (categoryId, categoryname) values (861, 'Landscaping & Irrigation');
insert into category (categoryId, categoryname) values (862, 'Painting & Vinyl Wall Covering');
insert into category (categoryId, categoryname) values (863, 'Hard Tile & Stone');
insert into category (categoryId, categoryname) values (864, 'Masonry');
insert into category (categoryId, categoryname) values (865, 'Framing (Wood)');
insert into category (categoryId, categoryname) values (866, 'Ornamental Railings');
insert into category (categoryId, categoryname) values (867, 'Doors, Frames & Hardware');
insert into category (categoryId, categoryname) values (868, 'Drilled Shafts');
insert into category (categoryId, categoryname) values (869, 'Termite Control');
insert into category (categoryId, categoryname) values (870, 'Elevator');
insert into category (categoryId, categoryname) values (871, 'Drilled Shafts');
insert into category (categoryId, categoryname) values (872, 'Curb & Gutter');
insert into category (categoryId, categoryname) values (873, 'Epoxy Flooring');
insert into category (categoryId, categoryname) values (874, 'Framing (Wood)');
insert into category (categoryId, categoryname) values (875, 'Asphalt Paving');
insert into category (categoryId, categoryname) values (876, 'Ornamental Railings');
insert into category (categoryId, categoryname) values (877, 'Construction Clean and Final Clean');
insert into category (categoryId, categoryname) values (878, 'Painting & Vinyl Wall Covering');
insert into category (categoryId, categoryname) values (879, 'Masonry & Precast');
insert into category (categoryId, categoryname) values (880, 'RF Shielding');
insert into category (categoryId, categoryname) values (881, 'Sitework & Site Utilities');
insert into category (categoryId, categoryname) values (882, 'Fire Sprinkler System');
insert into category (categoryId, categoryname) values (883, 'Structural and Misc Steel (Fabrication)');
insert into category (categoryId, categoryname) values (884, 'Retaining Wall and Brick Pavers');
insert into category (categoryId, categoryname) values (885, 'Plumbing & Medical Gas');
insert into category (categoryId, categoryname) values (886, 'Sitework & Site Utilities');
insert into category (categoryId, categoryname) values (887, 'Retaining Wall and Brick Pavers');
insert into category (categoryId, categoryname) values (888, 'Roofing (Metal)');
insert into category (categoryId, categoryname) values (889, 'Wall Protection');
insert into category (categoryId, categoryname) values (890, 'Electrical and Fire Alarm');
insert into category (categoryId, categoryname) values (891, 'Marlite Panels (FED)');
insert into category (categoryId, categoryname) values (892, 'Masonry');
insert into category (categoryId, categoryname) values (893, 'Casework');
insert into category (categoryId, categoryname) values (894, 'Retaining Wall and Brick Pavers');
insert into category (categoryId, categoryname) values (895, 'Drywall & Acoustical (MOB)');
insert into category (categoryId, categoryname) values (896, 'Rebar & Wire Mesh Install');
insert into category (categoryId, categoryname) values (897, 'Roofing (Metal)');
insert into category (categoryId, categoryname) values (898, 'Exterior Signage');
insert into category (categoryId, categoryname) values (899, 'Electrical and Fire Alarm');
insert into category (categoryId, categoryname) values (900, 'Epoxy Flooring');
insert into category (categoryId, categoryname) values (901, 'Casework');
insert into category (categoryId, categoryname) values (902, 'Doors, Frames & Hardware');
insert into category (categoryId, categoryname) values (903, 'Masonry & Precast');
insert into category (categoryId, categoryname) values (904, 'Elevator');
insert into category (categoryId, categoryname) values (905, 'Termite Control');
insert into category (categoryId, categoryname) values (906, 'EIFS');
insert into category (categoryId, categoryname) values (907, 'Site Furnishings');
insert into category (categoryId, categoryname) values (908, 'Retaining Wall and Brick Pavers');
insert into category (categoryId, categoryname) values (909, 'Drilled Shafts');
insert into category (categoryId, categoryname) values (910, 'EIFS');
insert into category (categoryId, categoryname) values (911, 'Rebar & Wire Mesh Install');
insert into category (categoryId, categoryname) values (912, 'Drywall & Acoustical (MOB)');
insert into category (categoryId, categoryname) values (913, 'Granite Surfaces');
insert into category (categoryId, categoryname) values (914, 'EIFS');
insert into category (categoryId, categoryname) values (915, 'Structural and Misc Steel (Fabrication)');
insert into category (categoryId, categoryname) values (916, 'RF Shielding');
insert into category (categoryId, categoryname) values (917, 'Glass & Glazing');
insert into category (categoryId, categoryname) values (918, 'Waterproofing & Caulking');
insert into category (categoryId, categoryname) values (919, 'Soft Flooring and Base');
insert into category (categoryId, categoryname) values (920, 'Drywall & Acoustical (FED)');
insert into category (categoryId, categoryname) values (921, 'RF Shielding');
insert into category (categoryId, categoryname) values (922, 'Drywall & Acoustical (FED)');
insert into category (categoryId, categoryname) values (923, 'RF Shielding');
insert into category (categoryId, categoryname) values (924, 'Elevator');
insert into category (categoryId, categoryname) values (925, 'Masonry');
insert into category (categoryId, categoryname) values (926, 'Construction Clean and Final Clean');
insert into category (categoryId, categoryname) values (927, 'Hard Tile & Stone');
insert into category (categoryId, categoryname) values (928, 'Casework');
insert into category (categoryId, categoryname) values (929, 'Termite Control');
insert into category (categoryId, categoryname) values (930, 'Waterproofing & Caulking');
insert into category (categoryId, categoryname) values (931, 'Construction Clean and Final Clean');
insert into category (categoryId, categoryname) values (932, 'EIFS');
insert into category (categoryId, categoryname) values (933, 'Structural & Misc Steel Erection');
insert into category (categoryId, categoryname) values (934, 'Wall Protection');
insert into category (categoryId, categoryname) values (935, 'Curb & Gutter');
insert into category (categoryId, categoryname) values (936, 'Landscaping & Irrigation');
insert into category (categoryId, categoryname) values (937, 'Exterior Signage');
insert into category (categoryId, categoryname) values (938, 'Structural and Misc Steel (Fabrication)');
insert into category (categoryId, categoryname) values (939, 'Granite Surfaces');
insert into category (categoryId, categoryname) values (940, 'Granite Surfaces');
insert into category (categoryId, categoryname) values (941, 'Landscaping & Irrigation');
insert into category (categoryId, categoryname) values (942, 'Construction Clean and Final Clean');
insert into category (categoryId, categoryname) values (943, 'Ornamental Railings');
insert into category (categoryId, categoryname) values (944, 'Hard Tile & Stone');
insert into category (categoryId, categoryname) values (945, 'Masonry');
insert into category (categoryId, categoryname) values (946, 'Framing (Steel)');
insert into category (categoryId, categoryname) values (947, 'Site Furnishings');
insert into category (categoryId, categoryname) values (948, 'Structural & Misc Steel Erection');
insert into category (categoryId, categoryname) values (949, 'Roofing (Asphalt)');
insert into category (categoryId, categoryname) values (950, 'Casework');
insert into category (categoryId, categoryname) values (951, 'Framing (Steel)');
insert into category (categoryId, categoryname) values (952, 'Roofing (Asphalt)');
insert into category (categoryId, categoryname) values (953, 'EIFS');
insert into category (categoryId, categoryname) values (954, 'Drilled Shafts');
insert into category (categoryId, categoryname) values (955, 'Ornamental Railings');
insert into category (categoryId, categoryname) values (956, 'Sitework & Site Utilities');
insert into category (categoryId, categoryname) values (957, 'Marlite Panels (FED)');
insert into category (categoryId, categoryname) values (958, 'Structural and Misc Steel (Fabrication)');
insert into category (categoryId, categoryname) values (959, 'Marlite Panels (FED)');
insert into category (categoryId, categoryname) values (960, 'Fire Sprinkler System');
insert into category (categoryId, categoryname) values (961, 'Overhead Doors');
insert into category (categoryId, categoryname) values (962, 'Roofing (Asphalt)');
insert into category (categoryId, categoryname) values (963, 'Electrical');
insert into category (categoryId, categoryname) values (964, 'Hard Tile & Stone');
insert into category (categoryId, categoryname) values (965, 'Roofing (Metal)');
insert into category (categoryId, categoryname) values (966, 'Plumbing & Medical Gas');
insert into category (categoryId, categoryname) values (967, 'Exterior Signage');
insert into category (categoryId, categoryname) values (968, 'Doors, Frames & Hardware');
insert into category (categoryId, categoryname) values (969, 'Sitework & Site Utilities');
insert into category (categoryId, categoryname) values (970, 'Fire Sprinkler System');
insert into category (categoryId, categoryname) values (971, 'Structural & Misc Steel Erection');
insert into category (categoryId, categoryname) values (972, 'Site Furnishings');
insert into category (categoryId, categoryname) values (973, 'Glass & Glazing');
insert into category (categoryId, categoryname) values (974, 'Overhead Doors');
insert into category (categoryId, categoryname) values (975, 'Soft Flooring and Base');
insert into category (categoryId, categoryname) values (976, 'Fire Sprinkler System');
insert into category (categoryId, categoryname) values (977, 'Wall Protection');
insert into category (categoryId, categoryname) values (978, 'Ornamental Railings');
insert into category (categoryId, categoryname) values (979, 'Framing (Wood)');
insert into category (categoryId, categoryname) values (980, 'EIFS');
insert into category (categoryId, categoryname) values (981, 'Wall Protection');
insert into category (categoryId, categoryname) values (982, 'Epoxy Flooring');
insert into category (categoryId, categoryname) values (983, 'Doors, Frames & Hardware');
insert into category (categoryId, categoryname) values (984, 'Drywall & Acoustical (FED)');
insert into category (categoryId, categoryname) values (985, 'EIFS');
insert into category (categoryId, categoryname) values (986, 'Marlite Panels (FED)');
insert into category (categoryId, categoryname) values (987, 'Wall Protection');
insert into category (categoryId, categoryname) values (988, 'Roofing (Asphalt)');
insert into category (categoryId, categoryname) values (989, 'Masonry & Precast');
insert into category (categoryId, categoryname) values (990, 'Drilled Shafts');
insert into category (categoryId, categoryname) values (991, 'Rebar & Wire Mesh Install');
insert into category (categoryId, categoryname) values (992, 'Fire Protection');
insert into category (categoryId, categoryname) values (993, 'Soft Flooring and Base');
insert into category (categoryId, categoryname) values (994, 'Curb & Gutter');
insert into category (categoryId, categoryname) values (995, 'Granite Surfaces');
insert into category (categoryId, categoryname) values (996, 'Wall Protection');
insert into category (categoryId, categoryname) values (997, 'Casework');
insert into category (categoryId, categoryname) values (998, 'Asphalt Paving');
insert into category (categoryId, categoryname) values (999, 'Construction Clean and Final Clean');
insert into category (categoryId, categoryname) values (1000, 'Rebar & Wire Mesh Install');
